---
title: "VIPVIZA-LPL"
output:
  github_document:
    toc: true
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r clearenvironment, include=FALSE}
rm(list = ls())
```

```{r, include=FALSE}
# Data path (hard coded file path).
markdown_path <- "~/projekt_data/2019-03-11_VIPVIZA-ITC_data/rData/markdown.RData"
# Load data:
load(markdown_path)
# Library
library(ggplot2)
```

# Preprocessing
## NMR
### A. Pre-imputation diagnostics

Percent missing:

```{r}
dim(unproc_samplemeta)
tempdata_dataMatrix$data$percent_missing
```

### B. Post-imputation diagnostics

```{r, fig.height=7, fig.width=7}
tempdata_dataMatrix$plots$scatter
tempdata_dataMatrix$plots$density
```

### C. Outlier analysis

PCA:

```{r, fig.height=7, fig.width=7}
c_id <- data.frame(
  row_n = seq(1, nrow(missData.dataMatrix))
)

plot_pca(
  Filter(is.numeric, missData.dataMatrix),
  c = c_id
)$scores_plot

plot_pca(
  Filter(is.numeric, missData.dataMatrix),
  c = c_id
)$loadings_plot
```


Column-wise boxplot:

```{r, fig.height=7, fig.width=7}
geom_cwiseboxplot(
  x = Filter(is.numeric, missData.dataMatrix),
  c = c_id[,1]
)
```

# Session info
```{r}
sessionInfo()
```